apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapp-deployment
  labels:
    app: sapp-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sapp-application
  template:
    metadata:
      labels:
        app: sapp-application
    spec:
      containers:
        - name: sapp-application
          image: europe-west2-docker.pkg.dev/zora-hackathon/sapp-production/sapp-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://testing_owner:npg_hrSRKItY39Vd@ep-nameless-wind-a560j4gl-pooler.us-east-2.aws.neon.tech/testing?sslmode=require"
            - name: LANGSMITH_PROJECT
              value: "pr-candid-fly-64"
            - name: LANGSMITH_ENDPOINT
              value: "https://api.smith.langchain.com"
            - name: LANGSMITH_TRACING
              value: "true"
            - name: LANGSMITH_API_KEY
              value: "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"
            - name: OPENAI_API_KEY
              value: "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"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "3000m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always