version: "3.8"
services:
  python-app:
    build: .
    container_name: python-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://testing_owner:npg_hrSRKItY39Vd@ep-nameless-wind-a560j4gl-pooler.us-east-2.aws.neon.tech/testing?sslmode=require
    command: ["uv", "run", "fastapi", "dev", "main.py", "--host=0.0.0.0", "--port=8000"]
