version: "3.8"
services:
  python-app:
    build: .
    container_name: python-app
    ports:
      - "8000:8000"
    environment:
      - LANGSMITH_PROJECT=
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_TRACING=true
      - LANGSMITH_API_KEY=
      - OPENAI_API_KEY=
      - DATABASE_URL=
    command: ["uv", "run", "fastapi", "dev", "main.py", "--host=0.0.0.0", "--port=8000"]
