/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppGenerateIdeasImport } from './routes/app/generate-ideas'
import { Route as AppAnalyseProfileImport } from './routes/app/analyse-profile'
import { Route as AppAnalyseCoinImport } from './routes/app/analyse-coin'
import { Route as AppReportsIndexImport } from './routes/app/reports/index'
import { Route as AppReportsReportIdImport } from './routes/app/reports/$reportId'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppGenerateIdeasRoute = AppGenerateIdeasImport.update({
  id: '/app/generate-ideas',
  path: '/app/generate-ideas',
  getParentRoute: () => rootRoute,
} as any)

const AppAnalyseProfileRoute = AppAnalyseProfileImport.update({
  id: '/app/analyse-profile',
  path: '/app/analyse-profile',
  getParentRoute: () => rootRoute,
} as any)

const AppAnalyseCoinRoute = AppAnalyseCoinImport.update({
  id: '/app/analyse-coin',
  path: '/app/analyse-coin',
  getParentRoute: () => rootRoute,
} as any)

const AppReportsIndexRoute = AppReportsIndexImport.update({
  id: '/app/reports/',
  path: '/app/reports/',
  getParentRoute: () => rootRoute,
} as any)

const AppReportsReportIdRoute = AppReportsReportIdImport.update({
  id: '/app/reports/$reportId',
  path: '/app/reports/$reportId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/app/analyse-coin': {
      id: '/app/analyse-coin'
      path: '/app/analyse-coin'
      fullPath: '/app/analyse-coin'
      preLoaderRoute: typeof AppAnalyseCoinImport
      parentRoute: typeof rootRoute
    }
    '/app/analyse-profile': {
      id: '/app/analyse-profile'
      path: '/app/analyse-profile'
      fullPath: '/app/analyse-profile'
      preLoaderRoute: typeof AppAnalyseProfileImport
      parentRoute: typeof rootRoute
    }
    '/app/generate-ideas': {
      id: '/app/generate-ideas'
      path: '/app/generate-ideas'
      fullPath: '/app/generate-ideas'
      preLoaderRoute: typeof AppGenerateIdeasImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/reports/$reportId': {
      id: '/app/reports/$reportId'
      path: '/app/reports/$reportId'
      fullPath: '/app/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdImport
      parentRoute: typeof rootRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/analyse-coin': typeof AppAnalyseCoinRoute
  '/app/analyse-profile': typeof AppAnalyseProfileRoute
  '/app/generate-ideas': typeof AppGenerateIdeasRoute
  '/app': typeof AppIndexRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/reports': typeof AppReportsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/analyse-coin': typeof AppAnalyseCoinRoute
  '/app/analyse-profile': typeof AppAnalyseProfileRoute
  '/app/generate-ideas': typeof AppGenerateIdeasRoute
  '/app': typeof AppIndexRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/reports': typeof AppReportsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/analyse-coin': typeof AppAnalyseCoinRoute
  '/app/analyse-profile': typeof AppAnalyseProfileRoute
  '/app/generate-ideas': typeof AppGenerateIdeasRoute
  '/app/': typeof AppIndexRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/reports/': typeof AppReportsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/app/analyse-coin'
    | '/app/analyse-profile'
    | '/app/generate-ideas'
    | '/app'
    | '/app/reports/$reportId'
    | '/app/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/app/analyse-coin'
    | '/app/analyse-profile'
    | '/app/generate-ideas'
    | '/app'
    | '/app/reports/$reportId'
    | '/app/reports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/app/analyse-coin'
    | '/app/analyse-profile'
    | '/app/generate-ideas'
    | '/app/'
    | '/app/reports/$reportId'
    | '/app/reports/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AppAnalyseCoinRoute: typeof AppAnalyseCoinRoute
  AppAnalyseProfileRoute: typeof AppAnalyseProfileRoute
  AppGenerateIdeasRoute: typeof AppGenerateIdeasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AppAnalyseCoinRoute: AppAnalyseCoinRoute,
  AppAnalyseProfileRoute: AppAnalyseProfileRoute,
  AppGenerateIdeasRoute: AppGenerateIdeasRoute,
  AppIndexRoute: AppIndexRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/register",
        "/app/analyse-coin",
        "/app/analyse-profile",
        "/app/generate-ideas",
        "/app/",
        "/app/reports/$reportId",
        "/app/reports/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/app/analyse-coin": {
      "filePath": "app/analyse-coin.tsx"
    },
    "/app/analyse-profile": {
      "filePath": "app/analyse-profile.tsx"
    },
    "/app/generate-ideas": {
      "filePath": "app/generate-ideas.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    },
    "/app/reports/$reportId": {
      "filePath": "app/reports/$reportId.tsx"
    },
    "/app/reports/": {
      "filePath": "app/reports/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
