name: Deploy to GKE Production on Merge
on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE=europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/sapp-production/sapp-application:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT }}

      - name: Set Image for GKE
        run: kubectl set image deployment/sapp-deployment sapp-application=europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/sapp-production/sapp-application:latest

      - name: Apply to GKE for Deploy
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment sapp-deployment
